# docker-compose.yml
version: "3"
services:
  scraper:
    build: .
    depends_on:
      - pg
    links:
      - pg
    environment:
      DB_URI: postgres://user:pass@pg:5432/test
  pg:
    container_name: pg
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    expose:
      - 5432
